[package]
name = "tui"
version = "0.5.0"
edition = "2021"
authors = ["Fulrix"]

[dependencies]
shared = { workspace = true }
ratatui = { workspace = true }
color-eyre = { workspace = true }
crossterm = { workspace = true }
tokio = { workspace = true }
