[package]
name = "pylot"
version = "0.4.4"
edition = "2021"
authors = ["Fulrix"]

[dependencies]
shared = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
clap_complete = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }

[dev-dependencies]
assert_cli = "0.6"
shellexpand = "3.1"
